connections = []
connections.append(('VANCOUVER', 3, 'CALGARY'))
connections.append(('VANCOUVER', 1, 'SEATTLE'))
connections.append(('VANCOUVER', 1, 'SEATTLE'))
connections.append(('CALGARY', 4, 'SEATTLE'))
connections.append(('CALGARY', 4, 'HELENA'))
connections.append(('CALGARY', 6, 'WINNIPEG'))
connections.append(('SEATTLE', 6, 'HELENA'))
connections.append(('SEATTLE', 1, 'PORTLAND'))
connections.append(('SEATTLE', 1, 'PORTLAND'))
connections.append(('HELENA', 4, 'WINNIPEG'))
connections.append(('HELENA', 6, 'DULUTH'))
connections.append(('HELENA', 5, 'OMAHA'))
connections.append(('HELENA', 4, 'DENVER'))
connections.append(('HELENA', 3, 'SALT LAKE CITY'))
connections.append(('WINNIPEG', 6, 'SAULT ST. MARIE'))
connections.append(('WINNIPEG', 4, 'DULUTH'))
connections.append(('PORTLAND', 6, 'SALT LAKE CITY'))
connections.append(('PORTLAND', 5, 'SAN FRANCISCO'))
connections.append(('PORTLAND', 5, 'SAN FRANCISCO'))
connections.append(('DULUTH', 3, 'SAULT ST. MARIE'))
connections.append(('DULUTH', 6, 'TORONTO'))
connections.append(('DULUTH', 3, 'CHICAGO'))
connections.append(('DULUTH', 2, 'OMAHA'))
connections.append(('DULUTH', 2, 'OMAHA'))
connections.append(('OMAHA', 4, 'CHICAGO'))
connections.append(('OMAHA', 1, 'KANSAS CITY'))
connections.append(('OMAHA', 1, 'KANSAS CITY'))
connections.append(('OMAHA', 4, 'DENVER'))
connections.append(('DENVER', 4, 'KANSAS CITY'))
connections.append(('DENVER', 4, 'KANSAS CITY'))
connections.append(('DENVER', 4, 'OKLAHOMA CITY'))
connections.append(('DENVER', 2, 'SANTA FE'))
connections.append(('DENVER', 5, 'PHOENIX'))
connections.append(('DENVER', 3, 'SALT LAKE CITY'))
connections.append(('DENVER', 3, 'SALT LAKE CITY'))
connections.append(('SALT LAKE CITY', 3, 'LAS VEGAS'))
connections.append(('SALT LAKE CITY', 4, 'SAN FRANCISCO'))
connections.append(('SALT LAKE CITY', 4, 'SAN FRANCISCO'))
connections.append(('SAULT ST. MARIE', 5, 'MONTREAL'))
connections.append(('SAULT ST. MARIE', 2, 'TORONTO'))
connections.append(('SAN FRANCISCO', 3, 'LOS ANGELES'))
connections.append(('SAN FRANCISCO', 3, 'LOS ANGELES'))
connections.append(('TORONTO', 3, 'MONTREAL'))
connections.append(('TORONTO', 2, 'PITTSBURGH'))
connections.append(('TORONTO', 4, 'CHICAGO'))
connections.append(('CHICAGO', 3, 'PITTSBURGH'))
connections.append(('CHICAGO', 3, 'PITTSBURGH'))
connections.append(('CHICAGO', 2, 'SAINT LOUIS'))
connections.append(('CHICAGO', 2, 'SAINT LOUIS'))
connections.append(('KANSAS CITY', 2, 'SAINT LOUIS'))
connections.append(('KANSAS CITY', 2, 'SAINT LOUIS'))
connections.append(('KANSAS CITY', 2, 'OKLAHOMA CITY'))
connections.append(('KANSAS CITY', 2, 'OKLAHOMA CITY'))
connections.append(('OKLAHOMA CITY', 2, 'LITTLE ROCK'))
connections.append(('OKLAHOMA CITY', 2, 'DALLAS'))
connections.append(('OKLAHOMA CITY', 2, 'DALLAS'))
connections.append(('OKLAHOMA CITY', 5, 'EL PASO'))
connections.append(('OKLAHOMA CITY', 3, 'SANTA FE'))
connections.append(('SANTA FE', 2, 'EL PASO'))
connections.append(('SANTA FE', 3, 'PHOENIX'))
connections.append(('PHOENIX', 3, 'EL PASO'))
connections.append(('PHOENIX', 3, 'LOS ANGELES'))
connections.append(('LAS VEGAS', 2, 'LOS ANGELES'))
connections.append(('MONTREAL', 2, 'BOSTON'))
connections.append(('MONTREAL', 2, 'BOSTON'))
connections.append(('MONTREAL', 3, 'NEW YORK'))
connections.append(('LOS ANGELES', 6, 'EL PASO'))
connections.append(('PITTSBURGH', 2, 'NEW YORK'))
connections.append(('PITTSBURGH', 2, 'NEW YORK'))
connections.append(('PITTSBURGH', 2, 'WASHINGTON'))
connections.append(('PITTSBURGH', 2, 'RALEIGH'))
connections.append(('PITTSBURGH', 4, 'NASHVILLE'))
connections.append(('PITTSBURGH', 5, 'SAINT LOUIS'))
connections.append(('SAINT LOUIS', 2, 'NASHVILLE'))
connections.append(('SAINT LOUIS', 2, 'LITTLE ROCK'))
connections.append(('LITTLE ROCK', 3, 'NASHVILLE'))
connections.append(('LITTLE ROCK', 3, 'NEW ORLEANS'))
connections.append(('LITTLE ROCK', 2, 'DALLAS'))
connections.append(('DALLAS', 1, 'HOUSTON'))
connections.append(('DALLAS', 1, 'HOUSTON'))
connections.append(('DALLAS', 4, 'EL PASO'))
connections.append(('EL PASO', 6, 'HOUSTON'))
connections.append(('BOSTON', 2, 'NEW YORK'))
connections.append(('BOSTON', 2, 'NEW YORK'))
connections.append(('NEW YORK', 2, 'WASHINGTON'))
connections.append(('NEW YORK', 2, 'WASHINGTON'))
connections.append(('WASHINGTON', 2, 'RALEIGH'))
connections.append(('WASHINGTON', 2, 'RALEIGH'))
connections.append(('RALEIGH', 2, 'CHARLESTON'))
connections.append(('RALEIGH', 2, 'ATLANTA'))
connections.append(('RALEIGH', 2, 'ATLANTA'))
connections.append(('RALEIGH', 3, 'NASHVILLE'))
connections.append(('NASHVILLE', 1, 'ATLANTA'))
connections.append(('NEW ORLEANS', 4, 'ATLANTA'))
connections.append(('NEW ORLEANS', 4, 'ATLANTA'))
connections.append(('NEW ORLEANS', 6, 'MIAMI'))
connections.append(('NEW ORLEANS', 2, 'HOUSTON'))
connections.append(('ATLANTA', 2, 'CHARLESTON'))
connections.append(('ATLANTA', 5, 'MIAMI'))
connections.append(('CHARLESTON', 4, 'MIAMI'))